title: TNTU-Net: A Semantic Segmentation Model for Autonomous Driving
description: Project page by Jinwen Sun and Wei Han for CS766 Computer Vision
show_downloads: false
google_analytics:
github:
  owner_name: Jinwen Sun
theme: jekyll-theme-cayman
